{"instance_id": "UDMIS067EXT", "instance_filename": "UDMIS067EXT_100_N100_W1.0_R0.1.qubo.json", "solver_name": "QUBODwaveSolver", "args": ["1000", "None", "None"], "timestamps": {"start": 1700862077.826419, "end": 1700862080.080029}, "solver": {"exception": "", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\admin\\Documents\\qopt\\benchmark\\bench.py\", line 152, in run\n    solver = self._run(instance_id, *args)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\Documents\\qopt\\benchmark\\bench_qubo.py\", line 108, in _run\n    sampler = DWaveSampler(token=self.token)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\system\\samplers\\dwave_sampler.py\", line 185, in __init__\n    self.solver = self._get_solver(penalty=self._solver_penalty)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\system\\samplers\\dwave_sampler.py\", line 200, in _get_solver\n    solvers = self.client.get_solvers(refresh=refresh, order_by=order_by, **filters)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\events.py\", line 105, in wrapped\n    rval = fn(*pargs, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\client\\base.py\", line 1165, in get_solvers\n    solvers = self._fetch_solvers(**query)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\utils.py\", line 489, in wrapper\n    val = fn(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\client\\base.py\", line 820, in _fetch_solvers\n    solver = solver_class(self, solver_desc)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\solver.py\", line 769, in __init__\n    self.edges = self.couplers = set(tuple(edge) for edge in self._encoding_couplers) | \\\n                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nMemoryError\n", "fail_timestamp": 1700862080.080029}, "success": false, "version": "2.0.2"}