{"instance_id": "UDMIS103EXT", "instance_filename": "UDMIS103EXT_100_N100_W1.0_R0.2.qubo.json", "solver_name": "QUBODwaveSolver", "args": ["1000", "None", "None"], "timestamps": {"start": 1700862084.607824, "end": 1700862086.746077}, "solver": {"exception": "", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\admin\\Documents\\qopt\\benchmark\\bench.py\", line 152, in run\n    solver = self._run(instance_id, *args)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\Documents\\qopt\\benchmark\\bench_qubo.py\", line 108, in _run\n    sampler = DWaveSampler(token=self.token)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\system\\samplers\\dwave_sampler.py\", line 185, in __init__\n    self.solver = self._get_solver(penalty=self._solver_penalty)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\system\\samplers\\dwave_sampler.py\", line 200, in _get_solver\n    solvers = self.client.get_solvers(refresh=refresh, order_by=order_by, **filters)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\events.py\", line 105, in wrapped\n    rval = fn(*pargs, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\client\\base.py\", line 1165, in get_solvers\n    solvers = self._fetch_solvers(**query)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\utils.py\", line 489, in wrapper\n    val = fn(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\client\\base.py\", line 802, in _fetch_solvers\n    data = Client._sapi_request(self.session.get, url)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\client\\base.py\", line 1770, in _sapi_request\n    caller, response.status_code, response.text)\n                                  ^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\requests\\models.py\", line 928, in text\n    encoding = self.apparent_encoding\n               ^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\requests\\models.py\", line 793, in apparent_encoding\n    return chardet.detect(self.content)[\"encoding\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\charset_normalizer\\legacy.py\", line 36, in detect\n    r = from_bytes(byte_str).best()\n        ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\charset_normalizer\\api.py\", line 230, in from_bytes\n    decoded_payload = str(\n                      ^^^^\nMemoryError\n", "fail_timestamp": 1700862086.730519}, "success": false, "version": "2.0.2"}