{"instance_id": "UDMIS003EXT", "instance_filename": "UDMIS003EXT_15_N15_W1.0_R0.2.qubo.json", "solver_name": "QUBOIBMSolver", "args": ["{'maxiter': 50}", "BOBYQA", "3", "0", "3", "0", "3", "1000", "100", "ibm_cusco", "ibm_quantum", "ibm-q-fraunhofer/fhg-all/fitw01", "8h", "False", "1", "1"], "timestamps": {"start": 1700450131.057876, "end": 1700484676.03453}, "solver": {"exception": "'RAN TOO LONG'", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\admin\\Documents\\qopt\\benchmark\\bench.py\", line 152, in run\n    solver = self._run(instance_id, *args)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\Documents\\qopt\\benchmark\\bench_qubo.py\", line 268, in _run\n    job_result = job.result()\n                 ^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\qiskit_ibm_runtime\\runtime_job.py\", line 221, in result\n    raise RuntimeJobMaxTimeoutError(error_message)\nqiskit_ibm_runtime.exceptions.RuntimeJobMaxTimeoutError: 'RAN TOO LONG'\n", "fail_timestamp": 1700484676.03453}, "success": false, "version": "2.0.2"}